version: "3.8"

services:
  postgres_db:
    image: postgres:16.2
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres@123}
      POSTGRES_DB: ${DB_NAME:-identity_reconciliation}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data in case of container restart
    networks:
      - identity-network

  app:
    container_name: identity-reconciliation-app
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-dev}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules 
    env_file:
      - ./.env
    environment:
      DB_HOST: ${DB_HOST:-postgres_db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-identity_reconciliation}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres@123}
    networks:
      - identity-network
    depends_on:
      - postgres_db

volumes:
  db_data:

networks:
  identity-network:
